### ISSUE TITLE
Clarify License.md so that MIT Licence is clear

### ISSUE THREAD

**Issue by sladen** [Microsoft/Font-Validator#3]
The present wording is of the code's licence is:
* https://github.com/Microsoft/Font-Validator/blob/master/License.md
```
  Copyright (c) Microsoft Corporation
  All rights reserved.
  MIT License
  Permission is hereby granted…
```
Ideally the apparent contradiction between `All rights reserved.` and `MIT License…`.  This may be possible by dropping the `All rights reserved` leaving the clear copyright and licence text/permission.

**Comment by aaronbell** [comment]
Thanks for the suggestion! At this time, we have to keep the license text as-is.
