### ISSUE TITLE
Warn on post table version 3

### ISSUE THREAD

**Issue by HinTak** [Microsoft/Font-Validator#47]
Currently it is a pass. Should warn on it:

http://typedrawers.com/discussion/1945/truetype-based-fonts-and-post-table-version-3-0

**Comment by khaledhosny** [comment]
And that warning would be based on what spec?

**Comment by HinTak** [comment]
Apple's. post v3 is clearly a problem with *some* rendering engine; and Apple's did clearly forewarn it.

I hope this is not arguing for the sake of arguing. AFAIC, any issues which is clearly a problem with *some*/*any* common rendering engines, should have a warning. Regardless of spec. It is up to the font designer to decide to ignore such warnings.

**Comment by khaledhosny** [comment]
So fonts that is fully spec-complaint would produce warnings because some program some where is buggy? It is much easier to reduce this to a single warning “_This is a font file, some application somewhere will handle some aspect of it incorrectly. You have been warned_”, and call it a day.

**Comment by davelab6** [comment]
Khaled, kindly I agree with hin-tak, warning for non spec issues is fine.
Erroring for spec issues is appropriate

On Jan 22, 2017 4:18 PM, "Khaled Hosny" <notifications@github.com> wrote:

So fonts that is fully spec-complaint would produce warnings because some
program some where is buggy? It is much easier to reduce this to a single
warning “*This is a font file, some application somewhere will handle some
aspect of it incorrectly. You have been warned*”, and call it a day.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/Font-Validator/issues/47#issuecomment-274360348>,
or mute the thread

**Comment by HinTak** [comment]
Firmware upgrades for printers (*some program*) is not a sensible demand to put upon users. Telling users that their printers have buggy firmware isn't practical, nor is asking users to upgrade/change OSes (again, *some program*) to get a better or correct rendering. 

I was hoping this is a simple issue for contributors to have a go.  Anyway, it is quicker for me to just make the change, than to respond to trolling.

Since FontVal runs stand-alone and just produces a report (and don't really do any actually rejecting/etc like otc), I'd just like the report to be as detailed as possible. It is up to the person reading the report to decide which parts are relevant to him/her; in the extreme case, he/she should stop reading the report if he/she does not see any item of interest.

**Comment by khaledhosny** [comment]
The printing stuff is red herring, it is just an outdated note in a decade old spec that Apple is not known for keeping it up to date.

The Apple issue that actually triggered this (http://typedrawers.com/discussion/1945/truetype-based-fonts-and-post-table-version-3-0) has nothing to do with printing. It is an undocumented autohinting feature that seems to depend on an unknown number of variables  and its extend is not even clear. Jumping quickly to just trigger warning here s premature at the best and even harmful on the long run as excessive unnecessary warnings tend to cause people to ignore them altogether and actually useful warnings become a needle in a haystack.

Not to mention that checking for `post` table version is not even enough, as evidenced from the forum discussion above, having glyph names other than what Apple expects (which is not clear either) will trigger the hinting issue. You can even have version 1 `post` table with 0 glyph names or partial coverage of the glyphs in the font, which will pass the check promoted here but still potentially trigger the autohinting issue (and the mythical printing issue).

**Comment by moyogo** [comment]
Good point Khaled, a post table version 1 can cause the bug just as well.

**Comment by HinTak** [comment]
I don't think so. The other post table version explicitly encodes the glyph names. Post table version 3 does not. hence the issue with non-conformant/unexpected glyph names.

Anyway, I am fine with adding more warnings on post table version 1 too, if you can identify such issues.

As I have repeated said a few times... I fully intend people to skip over and ignore part of the reports they don't like or think irrelevant to their usage. The warning message clearly says "Apple said...", so if you intend your fonts to work on microsoft platforms only or whatever, you are free to ignore it. Not sure why this is even worth going over and over about. The reports are meant to be as detailed as possible, as far as I am concerned. The reader decides what they want to do with that information.
